DEFAULT_GATEWAY_MAC = 48'b0
// ETH 0
ETH0_IP = 64'b0
ETHO_GW_MAC = ${DEFAULT_GATEWAY_MAC}

// ETH 1
ETH1_IP = 64'b1
ETH1_GW_MAC = ${DEFAULT_GATEWAY_MAC}

// ETH 2
ETH2_IP = 64'b2
ETH2_GW_MAC = ${DEFAULT_GATEWAY_MAC}

